# Generated by Django 6.0 on 2026-01-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHT', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dht11',
            name='dt',
            field=models.DateTimeField(),
        ),
    ]
