# Generated by Django 5.2.7 on 2025-12-13 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHT', '0002_alert_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seuil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_min', models.FloatField()),
                ('temp_max', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
