# Generated by Django 6.0 on 2026-01-03 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHT', '0003_alter_dht11_dt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('info', 'Information'), ('warning', 'Avertissement'), ('error', 'Erreur'), ('critical', 'Critique')], max_length=20, verbose_name='Niveau')),
                ('category', models.CharField(choices=[('system', 'Système'), ('temperature', 'Température'), ('humidity', 'Humidité'), ('incident', 'Incident'), ('user', 'Utilisateur'), ('sensor', 'Capteur')], max_length=20, verbose_name='Catégorie')),
                ('message', models.TextField(verbose_name='Message')),
                ('details', models.JSONField(blank=True, null=True, verbose_name='Détails')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log système',
                'verbose_name_plural': 'Logs système',
                'ordering': ['-created_at'],
            },
        ),
    ]
