# Generated by Django 5.2.7 on 2025-12-14 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHT', '0003_seuil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AddField(
            model_name='comment',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='DHT.ticket'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user_name',
            field=models.CharField(default='unknown', max_length=100),
        ),
    ]
